[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Riviera Docs"
authors = [{name = "D Kott", email = "dkott@colostate.edu"}]
dynamic = ["version", "description"]
